spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**
server:
  port: 1111

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6767/eureka/