spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_user_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6767/eureka/
server:
  port: 8081